/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as UjuzispeakRouteImport } from './routes/ujuzispeak'
import { Route as UjuzimindRouteImport } from './routes/ujuzimind'
import { Route as UjuziimpactRouteImport } from './routes/ujuziimpact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimulationsRouteImport } from './routes/simulations'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PronunciationRouteImport } from './routes/pronunciation'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PhrasebookRouteImport } from './routes/phrasebook'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as InstitutionsRouteImport } from './routes/institutions'
import { Route as GrammarRouteImport } from './routes/grammar'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailyChallengeRouteImport } from './routes/daily-challenge'
import { Route as CreatorStudioRouteImport } from './routes/creator-studio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScenariosScenarioIdRouteImport } from './routes/scenarios.$scenarioId'
import { Route as GamesMatchRouteImport } from './routes/games.match'
import { Route as FeedbackSessionIdRouteImport } from './routes/feedback.$sessionId'
import { Route as ChatScenarioIdRouteImport } from './routes/chat.$scenarioId'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const UjuzispeakRoute = UjuzispeakRouteImport.update({
  id: '/ujuzispeak',
  path: '/ujuzispeak',
  getParentRoute: () => rootRouteImport,
} as any)
const UjuzimindRoute = UjuzimindRouteImport.update({
  id: '/ujuzimind',
  path: '/ujuzimind',
  getParentRoute: () => rootRouteImport,
} as any)
const UjuziimpactRoute = UjuziimpactRouteImport.update({
  id: '/ujuziimpact',
  path: '/ujuziimpact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationsRoute = SimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationRoute = PronunciationRouteImport.update({
  id: '/pronunciation',
  path: '/pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PhrasebookRoute = PhrasebookRouteImport.update({
  id: '/phrasebook',
  path: '/phrasebook',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionsRoute = InstitutionsRouteImport.update({
  id: '/institutions',
  path: '/institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarRoute = GrammarRouteImport.update({
  id: '/grammar',
  path: '/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyChallengeRoute = DailyChallengeRouteImport.update({
  id: '/daily-challenge',
  path: '/daily-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorStudioRoute = CreatorStudioRouteImport.update({
  id: '/creator-studio',
  path: '/creator-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosScenarioIdRoute = ScenariosScenarioIdRouteImport.update({
  id: '/scenarios/$scenarioId',
  path: '/scenarios/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMatchRoute = GamesMatchRouteImport.update({
  id: '/games/match',
  path: '/games/match',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackSessionIdRoute = FeedbackSessionIdRouteImport.update({
  id: '/feedback/$sessionId',
  path: '/feedback/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatScenarioIdRoute = ChatScenarioIdRouteImport.update({
  id: '/chat/$scenarioId',
  path: '/chat/$scenarioId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/characters': typeof CharactersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creator-studio': typeof CreatorStudioRoute
  '/daily-challenge': typeof DailyChallengeRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/grammar': typeof GrammarRoute
  '/institutions': typeof InstitutionsRoute
  '/journal': typeof JournalRoute
  '/leaderboard': typeof LeaderboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partner': typeof PartnerRoute
  '/phrasebook': typeof PhrasebookRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/pronunciation': typeof PronunciationRoute
  '/quiz': typeof QuizRoute
  '/reading': typeof ReadingRoute
  '/share': typeof ShareRoute
  '/simulations': typeof SimulationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ujuziimpact': typeof UjuziimpactRoute
  '/ujuzimind': typeof UjuzimindRoute
  '/ujuzispeak': typeof UjuzispeakRoute
  '/vocabulary': typeof VocabularyRoute
  '/chat/$scenarioId': typeof ChatScenarioIdRoute
  '/feedback/$sessionId': typeof FeedbackSessionIdRoute
  '/games/match': typeof GamesMatchRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/characters': typeof CharactersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creator-studio': typeof CreatorStudioRoute
  '/daily-challenge': typeof DailyChallengeRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/grammar': typeof GrammarRoute
  '/institutions': typeof InstitutionsRoute
  '/journal': typeof JournalRoute
  '/leaderboard': typeof LeaderboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partner': typeof PartnerRoute
  '/phrasebook': typeof PhrasebookRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/pronunciation': typeof PronunciationRoute
  '/quiz': typeof QuizRoute
  '/reading': typeof ReadingRoute
  '/share': typeof ShareRoute
  '/simulations': typeof SimulationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ujuziimpact': typeof UjuziimpactRoute
  '/ujuzimind': typeof UjuzimindRoute
  '/ujuzispeak': typeof UjuzispeakRoute
  '/vocabulary': typeof VocabularyRoute
  '/chat/$scenarioId': typeof ChatScenarioIdRoute
  '/feedback/$sessionId': typeof FeedbackSessionIdRoute
  '/games/match': typeof GamesMatchRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/characters': typeof CharactersRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/creator-studio': typeof CreatorStudioRoute
  '/daily-challenge': typeof DailyChallengeRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/explore': typeof ExploreRoute
  '/grammar': typeof GrammarRoute
  '/institutions': typeof InstitutionsRoute
  '/journal': typeof JournalRoute
  '/leaderboard': typeof LeaderboardRoute
  '/opportunities': typeof OpportunitiesRoute
  '/partner': typeof PartnerRoute
  '/phrasebook': typeof PhrasebookRoute
  '/practice': typeof PracticeRoute
  '/progress': typeof ProgressRoute
  '/pronunciation': typeof PronunciationRoute
  '/quiz': typeof QuizRoute
  '/reading': typeof ReadingRoute
  '/share': typeof ShareRoute
  '/simulations': typeof SimulationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ujuziimpact': typeof UjuziimpactRoute
  '/ujuzimind': typeof UjuzimindRoute
  '/ujuzispeak': typeof UjuzispeakRoute
  '/vocabulary': typeof VocabularyRoute
  '/chat/$scenarioId': typeof ChatScenarioIdRoute
  '/feedback/$sessionId': typeof FeedbackSessionIdRoute
  '/games/match': typeof GamesMatchRoute
  '/scenarios/$scenarioId': typeof ScenariosScenarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/badges'
    | '/characters'
    | '/community'
    | '/contact'
    | '/creator-studio'
    | '/daily-challenge'
    | '/dashboard'
    | '/events'
    | '/explore'
    | '/grammar'
    | '/institutions'
    | '/journal'
    | '/leaderboard'
    | '/opportunities'
    | '/partner'
    | '/phrasebook'
    | '/practice'
    | '/progress'
    | '/pronunciation'
    | '/quiz'
    | '/reading'
    | '/share'
    | '/simulations'
    | '/sitemap.xml'
    | '/ujuziimpact'
    | '/ujuzimind'
    | '/ujuzispeak'
    | '/vocabulary'
    | '/chat/$scenarioId'
    | '/feedback/$sessionId'
    | '/games/match'
    | '/scenarios/$scenarioId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/badges'
    | '/characters'
    | '/community'
    | '/contact'
    | '/creator-studio'
    | '/daily-challenge'
    | '/dashboard'
    | '/events'
    | '/explore'
    | '/grammar'
    | '/institutions'
    | '/journal'
    | '/leaderboard'
    | '/opportunities'
    | '/partner'
    | '/phrasebook'
    | '/practice'
    | '/progress'
    | '/pronunciation'
    | '/quiz'
    | '/reading'
    | '/share'
    | '/simulations'
    | '/sitemap.xml'
    | '/ujuziimpact'
    | '/ujuzimind'
    | '/ujuzispeak'
    | '/vocabulary'
    | '/chat/$scenarioId'
    | '/feedback/$sessionId'
    | '/games/match'
    | '/scenarios/$scenarioId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/badges'
    | '/characters'
    | '/community'
    | '/contact'
    | '/creator-studio'
    | '/daily-challenge'
    | '/dashboard'
    | '/events'
    | '/explore'
    | '/grammar'
    | '/institutions'
    | '/journal'
    | '/leaderboard'
    | '/opportunities'
    | '/partner'
    | '/phrasebook'
    | '/practice'
    | '/progress'
    | '/pronunciation'
    | '/quiz'
    | '/reading'
    | '/share'
    | '/simulations'
    | '/sitemap.xml'
    | '/ujuziimpact'
    | '/ujuzimind'
    | '/ujuzispeak'
    | '/vocabulary'
    | '/chat/$scenarioId'
    | '/feedback/$sessionId'
    | '/games/match'
    | '/scenarios/$scenarioId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BadgesRoute: typeof BadgesRoute
  CharactersRoute: typeof CharactersRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CreatorStudioRoute: typeof CreatorStudioRoute
  DailyChallengeRoute: typeof DailyChallengeRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  ExploreRoute: typeof ExploreRoute
  GrammarRoute: typeof GrammarRoute
  InstitutionsRoute: typeof InstitutionsRoute
  JournalRoute: typeof JournalRoute
  LeaderboardRoute: typeof LeaderboardRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PartnerRoute: typeof PartnerRoute
  PhrasebookRoute: typeof PhrasebookRoute
  PracticeRoute: typeof PracticeRoute
  ProgressRoute: typeof ProgressRoute
  PronunciationRoute: typeof PronunciationRoute
  QuizRoute: typeof QuizRoute
  ReadingRoute: typeof ReadingRoute
  ShareRoute: typeof ShareRoute
  SimulationsRoute: typeof SimulationsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UjuziimpactRoute: typeof UjuziimpactRoute
  UjuzimindRoute: typeof UjuzimindRoute
  UjuzispeakRoute: typeof UjuzispeakRoute
  VocabularyRoute: typeof VocabularyRoute
  ChatScenarioIdRoute: typeof ChatScenarioIdRoute
  FeedbackSessionIdRoute: typeof FeedbackSessionIdRoute
  GamesMatchRoute: typeof GamesMatchRoute
  ScenariosScenarioIdRoute: typeof ScenariosScenarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujuzispeak': {
      id: '/ujuzispeak'
      path: '/ujuzispeak'
      fullPath: '/ujuzispeak'
      preLoaderRoute: typeof UjuzispeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujuzimind': {
      id: '/ujuzimind'
      path: '/ujuzimind'
      fullPath: '/ujuzimind'
      preLoaderRoute: typeof UjuzimindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ujuziimpact': {
      id: '/ujuziimpact'
      path: '/ujuziimpact'
      fullPath: '/ujuziimpact'
      preLoaderRoute: typeof UjuziimpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulations': {
      id: '/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation': {
      id: '/pronunciation'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof PronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phrasebook': {
      id: '/phrasebook'
      path: '/phrasebook'
      fullPath: '/phrasebook'
      preLoaderRoute: typeof PhrasebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutions': {
      id: '/institutions'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof InstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar': {
      id: '/grammar'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-challenge': {
      id: '/daily-challenge'
      path: '/daily-challenge'
      fullPath: '/daily-challenge'
      preLoaderRoute: typeof DailyChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-studio': {
      id: '/creator-studio'
      path: '/creator-studio'
      fullPath: '/creator-studio'
      preLoaderRoute: typeof CreatorStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios/$scenarioId': {
      id: '/scenarios/$scenarioId'
      path: '/scenarios/$scenarioId'
      fullPath: '/scenarios/$scenarioId'
      preLoaderRoute: typeof ScenariosScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/match': {
      id: '/games/match'
      path: '/games/match'
      fullPath: '/games/match'
      preLoaderRoute: typeof GamesMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback/$sessionId': {
      id: '/feedback/$sessionId'
      path: '/feedback/$sessionId'
      fullPath: '/feedback/$sessionId'
      preLoaderRoute: typeof FeedbackSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$scenarioId': {
      id: '/chat/$scenarioId'
      path: '/chat/$scenarioId'
      fullPath: '/chat/$scenarioId'
      preLoaderRoute: typeof ChatScenarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BadgesRoute: BadgesRoute,
  CharactersRoute: CharactersRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CreatorStudioRoute: CreatorStudioRoute,
  DailyChallengeRoute: DailyChallengeRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  ExploreRoute: ExploreRoute,
  GrammarRoute: GrammarRoute,
  InstitutionsRoute: InstitutionsRoute,
  JournalRoute: JournalRoute,
  LeaderboardRoute: LeaderboardRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PartnerRoute: PartnerRoute,
  PhrasebookRoute: PhrasebookRoute,
  PracticeRoute: PracticeRoute,
  ProgressRoute: ProgressRoute,
  PronunciationRoute: PronunciationRoute,
  QuizRoute: QuizRoute,
  ReadingRoute: ReadingRoute,
  ShareRoute: ShareRoute,
  SimulationsRoute: SimulationsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UjuziimpactRoute: UjuziimpactRoute,
  UjuzimindRoute: UjuzimindRoute,
  UjuzispeakRoute: UjuzispeakRoute,
  VocabularyRoute: VocabularyRoute,
  ChatScenarioIdRoute: ChatScenarioIdRoute,
  FeedbackSessionIdRoute: FeedbackSessionIdRoute,
  GamesMatchRoute: GamesMatchRoute,
  ScenariosScenarioIdRoute: ScenariosScenarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
